/**
 * @author
 * Håkon Ludvig Øisund <haakon@oisund.no>
 */

#ifndef AST_H
#define AST_H

#include "list.h"

#include <stddef.h>

typedef enum node_type {
    INVALID,
    ANDNOT,
    AND,
    OR,
    WORD
} nodetype_t;

typedef struct node node_t;
struct node {
    void* item;
    nodetype_t type;
    node_t* parent;
    node_t* left;
    node_t* right;
};

typedef struct ast {
    node_t* root;
} ast_t;

/**
 * @brief Creates a new, empty AST
 * @returns A pointer to the newly allocated AST, or `NULL` on failure
 */
ast_t* ast_create();

/**
 * @brief Parses a list of tokens to an AST
 * @param ast: pointer to an empty ast
 * @param query_tokens: pointer to list containing a query
 */
uint8_t ast_parse(ast_t* ast, list_t* query_tokens, char* errmsg);

/**
 * @brief Destroy an AST
 * @param ast: pointer to the AST to be destroyed
 */
void ast_destroy(ast_t* ast);

typedef struct tree_iterator tree_iterator_t;

/**
 * @brief Checks if value is an operator
 * @param value: a value to check
 * @returns 1 or 0
 */
uint8_t is_operator(void* value);

/**
 * @brief Creates a new iterator for AST
 * @param ast: pointer to AST to be iterated over
 * @returns pointer to the newly allocated tree iterator
 */
tree_iterator_t* ast_createiter(ast_t* ast);

/**
 * @brief Deallocates resources from a `tree_iterator_t`
 * @param iter: pointer to iteratar to be destroyed
 */
void ast_destroyiter(tree_iterator_t* iter);

/**
 * @brief checks if iterator has more items iterate
 * @param iter: pointer to an iterator
 * @returns 1 if iterator has next. 0 if not.
 */
uint8_t ast_hasnext(tree_iterator_t* iter);

/**
 * @brief goes to next element in tree
 * @param iter: pointer to iterator
 * @returns value of next item
 */
void* ast_next(tree_iterator_t* iter);

/**
 * @brief Prints an AST to terminal as a tree 
 * 
 * @note This function is generated by ChatGPT
 */
void print_tree(const ast_t* ast);

#endif /* AST_H */
